version: "3.9" # optional since v1.27.0
services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db-volume:/data/db
  api:
    container_name: api
    build:
      context: api/
      dockerfile: "Dockerfile"
    ports:
      - "5001:3001"
  web:
    container_name: web
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
volumes:
  mongo-db-volume:
    name: mongo-db-volume
networks:
  default:
    name: default-network
    driver: bridge
